### ISSUE TITLE
Cannot create node with label

### ISSUE THREAD

**Issue by DrD00der** [GraphStory/neo4j-ios#15]
In the current readme example, you create a node with label with:

    `node.addLabel("customLabelForNode_" + randomString)

    theo.createNode(node, completionBlock: {(node, error) in
        print("new node \(node)")
    });
`

In the TheoTest example however, it calls a different version of createNode():

            theo.createNode(node, labels: node.labels, completionBlock: {(_, error) in
            
            XCTAssertNil(error, "Error must be nil \(error?.description)")
            
            exp.fulfill()
        })

There is an extra call in there for node.labels.  However, if I try to use that I get an error saying Value of type "Node" has no member named 'labels'.  

I checked my Node.swift file and confirm the class doesn't have that member.  I'm wondering if the code is up to date on the github?  Or is there something else to get this to create properly?

**Comment by DrD00der** [comment]
On further eval, I do see the labels in the Node class:
public class Node {

    // MARK: Private Setters and Public Getters

    private (set) var nodeData: [String:AnyObject] = [String:AnyObject]()
    private (set) var labels: [String] = [String]()

Why isn't it recognizing that and adding it when the node is created?

**Comment by kwylez** [comment]
I'll dig into this in the morning.

**Comment by DrD00der** [comment]
Awesome thanks!

**Comment by kwylez** [comment]
@DrD00der my test instance (running 2.2.3) the unit test passes. I'm having my instance upgraded to 2.3.2 as we speak.

**Comment by kwylez** [comment]
I did find a *potential* bug, but need to add in some more logic and create a new branch for testing. I should have this done by the morning. The framework technically hasn't been tested with CE. Can you setup an instance on graphstory.com and run the unit tests against that as well?

**Comment by DrD00der** [comment]
I guess I can?  I don't have an account there so I'll have to sign up.  It's a free trial right?  

I can try it on my locally hosted server first and if that works well, can set up a trial to test it there too.

**Comment by kwylez** [comment]
@DrD00der I published the debug branch https://github.com/GraphStory/neo4j-ios/tree/issue/15. Please take a look at the changes. My unit test is passing and labels are being added to the label.

GraphStory does have a free account. Let me know if you need any help with that.

**Comment by DrD00der** [comment]
Still having the same issue, but I found a work around.  The problem is that xcode thinks that node does not have a member named labels.  Is that because it's a private setter?

        public class Node {
        // MARK: Private Setters and Public Getters
    
    private (set) var nodeData: [String:AnyObject] = [String:AnyObject]()
    private (set) var labels: [String] = [String]()


Instead of using the node.labels, if I place the label directly into the function call, it does create it properly:

        theo.createNode(node, labels: ["Label"], completionBlock: {(node, error) in
            print("new node \(node)")
        });

The workaround gets the job done, but I'm sure there is another way to clean it up.

**Comment by kwylez** [comment]
@DrD00der I think I know where the disconnect is. The methods and properties are working as they should, but how Neo4j deals with nodes and labels is what is causing issues. I'll type up the summary and update the ticket today.

The good thing is that your "workaround" really isn't a workaround, but **one** of the correct ways to use the `createNode(node:labels:completionBlock)` method.

**Comment by kwylez** [comment]
@DrD00der I should have caught this earlier so I apologize.

You were performing the following request expecting labels to be associated:

```
node.addLabel("customLabelForNode_" + randomString)

theo.createNode(node, completionBlock: {(node, error) in
    print("new node \(node)")
});
```
The labels **are** being added to the `Node` instance, but aren't saved on the object because Neo4j requires an API call to set those labels and `createNode` doesn't do that.

In the unit test I'm creating a local instance of a node, adding the labels and then calling 
https://github.com/GraphStory/neo4j-ios/blob/master/Source/Theo/Theo/Client.swift#L299

**Summary**

You can either set the labels explicitly on the node just like the unit test *or* you can set labels separately as you did above. It looks like I'll need to update the README for clarification and possibly change the `createNode` to method to detect labels on the node and create those as well.

Thoughts?

**Comment by DrD00der** [comment]
Gotcha.  Yeah I think updating the README is sufficient so people know how to add the labels.  If you want to change the createNode method you can do that, but updating the readme is a lot quicker and gets the job done!  

Thanks!

**Comment by kwylez** [comment]
@DrD00der thanks for the feedback and filing this. I'll merge this into master later today.

**Comment by DrD00der** [comment]
No, thank you for working on this!  

One last question - how do I pull data into an array format from a cypher query?  It appears to return JSON but it's in the form of the Cypher class.  If it were a string, I could parse the JSON into a swift array.  Is there a way to do that easily with the code?  Or is there a way to convert the cypher returned data into a string or NSData?
